version: '3.8'

services:
  backend:
    container_name: api
    build:
      context: ./backend
    image: setup/laradocker
    volumes:
      - ./backend:/var/www
    working_dir: /var/www/
    ports:
      - "9000:9000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=traydb
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app-network

  frontend:
    container_name: web 
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    networks:
      - app-network

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: traydb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    container_name: server
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
